# Generated by Django 5.1.6 on 2025-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_created_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
