# Generated by Django 5.1.6 on 2025-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_stock_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
