# Generated by Django 5.1.6 on 2025-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_stock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=150, null=True)),
                ('Category_Image', models.ImageField(null=True, upload_to='Category Image')),
            ],
        ),
    ]
