# Generated by Django 5.1.6 on 2025-02-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_stockcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcategory',
            old_name='Description',
            new_name='C_Description',
        ),
    ]
