# Generated by Django 5.1.6 on 2025-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_rename_description_stockcategory_c_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Item_Price',
            field=models.IntegerField(null=True),
        ),
    ]
