# Generated by Django 5.1.6 on 2025-02-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_stock_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRole',
        ),
    ]
