# Generated by Django 5.1.6 on 2025-02-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_rename_user_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
