# Generated by Django 5.1.6 on 2025-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='RationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ration', models.CharField(max_length=100)),
                ('R_Desc', models.CharField(max_length=150, null=True)),
                ('R_Quant', models.IntegerField()),
                ('R_Avail', models.CharField(max_length=50)),
                ('R_Price', models.IntegerField(null=True)),
                ('R_Image', models.ImageField(null=True, upload_to='Ration Image')),
            ],
        ),
    ]
