# Generated by Django 5.1.6 on 2025-02-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_rationitems'),
        ('WebApp', '0031_cartdb_ration_item_cartdb_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='WebApp.shopowner'),
        ),
    ]
