# Generated by Django 5.1.6 on 2025-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_stock_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Item_Image',
            field=models.ImageField(null=True, upload_to='Item Image'),
        ),
    ]
