# Generated by Django 5.1.6 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Name', models.CharField(max_length=100)),
                ('Ration_Card', models.CharField(max_length=100)),
                ('U_Mail', models.EmailField(max_length=100)),
                ('U_Mobile', models.CharField(max_length=20)),
                ('U_Pass', models.CharField(max_length=100)),
                ('C_Pass', models.CharField(max_length=100)),
            ],
        ),
    ]
