# Generated by Django 5.1.6 on 2025-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=100)),
                ('C_Mail', models.EmailField(max_length=100)),
                ('Phn_Num', models.CharField(max_length=100)),
                ('Mesg', models.CharField(max_length=150)),
            ],
        ),
    ]
