# Generated by Django 5.1.6 on 2025-02-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=100)),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Quantity', models.IntegerField()),
                ('I_Price', models.IntegerField()),
                ('I_Total', models.IntegerField()),
                ('Item_Image', models.ImageField(upload_to='Cart Images')),
            ],
        ),
    ]
