# Generated by Django 5.1.6 on 2025-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='Ration_Card',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
