# Generated by Django 5.1.6 on 2025-02-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_userregister_ration_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='BeneficiaryRegister',
        ),
    ]
