# Generated by Django 5.1.6 on 2025-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_rename_userregister_beneficiaryregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(max_length=100)),
                ('Reg_Num', models.CharField(max_length=100, unique=True)),
                ('S_Mail', models.EmailField(max_length=100)),
                ('S_Mobile', models.CharField(max_length=20)),
                ('S_Pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiaryregister',
            name='C_Pass',
        ),
    ]
