# Generated by Django 5.1.6 on 2025-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_shopowner_remove_beneficiaryregister_c_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregister',
            name='Card_Color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
