# Generated by Django 5.1.6 on 2025-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_beneficiaryregister_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Item_Quantity',
            field=models.IntegerField(null=True),
        ),
    ]
