# Generated by Django 5.1.6 on 2025-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_cartdb_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregister',
            name='Family_Members',
            field=models.IntegerField(null=True),
        ),
    ]
