# Generated by Django 5.1.6 on 2025-02-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
