# Generated by Django 5.1.6 on 2025-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ord_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
