# Generated by Django 5.1.6 on 2025-02-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_orderdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDB',
        ),
    ]
