# Generated by Django 5.1.6 on 2025-02-25 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_delete_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Num', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Card_Num', models.CharField(blank=True, max_length=100)),
                ('Reg_Num', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
