# Generated by Django 5.1.6 on 2025-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_orderdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Card_Num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='Reg_Num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
