# Generated by Django 5.1.6 on 2025-02-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_orderdb_card_num_alter_orderdb_reg_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='Name',
            new_name='User_Name',
        ),
    ]
