# Generated by Django 5.1.6 on 2025-02-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_rename_name_orderdb_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='User_Name',
            new_name='Name',
        ),
    ]
