# Generated by Django 5.1.6 on 2025-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_rename_user_name_orderdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='User_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
