# Generated by Django 5.1.6 on 2025-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_remove_orderdb_order_cartdb_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ord_Status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('out for delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='pending', max_length=100)),
            ],
        ),
    ]
