# Generated by Django 5.1.6 on 2025-02-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_order_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='User_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
