# Generated by Django 5.1.6 on 2025-02-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_order_booking_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='WebApp.orderdb'),
        ),
    ]
