# Generated by Django 5.1.6 on 2025-02-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_order_booking_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdb',
            options={'verbose_name': 'Cart Item'},
        ),
        migrations.AlterModelOptions(
            name='orderdb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order'},
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Card_Num',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Reg_Num',
        ),
        migrations.AddField(
            model_name='orderdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='User_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='WebApp.orderdb')),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.DeleteModel(
            name='Order_Booking',
        ),
    ]
