# Generated by Django 5.1.6 on 2025-02-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0024_alter_cartdb_options_alter_orderdb_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Card_Num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='Reg_Num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
