# Generated by Django 5.1.6 on 2025-02-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0025_orderdb_card_num_orderdb_reg_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Phone', models.CharField(max_length=20)),
                ('D_Partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('D_Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to='WebApp.shopowner', verbose_name='Shop Registration Number')),
            ],
        ),
    ]
