# Generated by Django 5.1.6 on 2025-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0026_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='C_PassW',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='PassW',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
