# Generated by Django 5.1.6 on 2025-02-27 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0028_remove_delivery_c_passw_remove_delivery_passw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryregister',
            name='U_Pass',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='S_Pass',
        ),
        migrations.AddField(
            model_name='beneficiaryregister',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopowner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
