# Generated by Django 5.1.6 on 2025-02-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0029_remove_beneficiaryregister_u_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='WebApp.shopowner'),
        ),
    ]
