# Generated by Django 5.1.6 on 2025-02-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_rationitems'),
        ('WebApp', '0030_orderdb_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='ration_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='AdminApp.rationitems'),
        ),
        migrations.AddField(
            model_name='cartdb',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='AdminApp.stock'),
        ),
    ]
