# Generated by Django 5.1.6 on 2025-03-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0031_cartdb_ration_item_cartdb_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='WebApp.orderdb'),
        ),
    ]
