# Generated by Django 5.1.6 on 2025-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0034_shopowner_district_shopowner_panchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregister',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
