# Generated by Django 5.1.6 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0036_beneficiaryregister_c_pass_shopowner_c_s_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='D_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Partner Image'),
        ),
    ]
