# Generated by Django 5.1.6 on 2025-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_delivery_d_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregister',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
