# Generated by Django 5.1.6 on 2025-03-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0038_beneficiaryregister_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='D_Pic',
        ),
    ]
