# Generated by Django 5.1.6 on 2025-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0039_remove_delivery_d_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='D_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Delivery Partner'),
        ),
    ]
