# Generated by Django 5.1.6 on 2025-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0040_delivery_d_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
