# Generated by Django 5.1.6 on 2025-03-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0041_alter_orderstatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Delivery_Partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='WebApp.delivery'),
        ),
    ]
