# Generated by Django 5.1.6 on 2025-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0044_remove_shopowner_c_s_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], default='COD', max_length=50),
        ),
    ]
