# Generated by Django 5.1.6 on 2025-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0045_orderdb_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
