# Generated by Django 5.1.6 on 2025-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0046_orderdb_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
