# Generated by Django 5.1.6 on 2025-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0048_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='I_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
