# Generated by Django 5.1.6 on 2025-02-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_orderdb_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='WebApp.orderdb'),
        ),
    ]
