# Generated by Django 5.1.6 on 2025-02-27 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0027_delivery_c_passw_delivery_passw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='C_PassW',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='PassW',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='D_Partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='D_Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partners', to='WebApp.shopowner'),
        ),
    ]
