# Generated by Django 5.1.6 on 2025-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0032_alter_cartdb_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregister',
            name='Shop_ID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
