# Generated by Django 5.1.6 on 2025-03-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0042_orderdb_delivery_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdb',
            name='Delivery_Partner',
        ),
    ]
