# Generated by Django 5.1.6 on 2025-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0043_remove_orderdb_delivery_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='C_S_Pass',
        ),
    ]
